version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./code/:/go/src/user-api
    depends_on:
      - database
    container_name: user-api-app
    command: sleep 72000
    networks:
      - app-network

  database:
    image: postgres:13.0
    restart: always
    container_name: user-api-db
    environment:
      POSTGRES_DB: open_market
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
