FROM golang:alpine

ENV GO111MODULE=on \
    TZ="Asia/Bangkok"

RUN apk add --update --no-cache \
    git \
    tzdata \ 
    && rm -rf /var/cache/apk/*

WORKDIR /go/src/user-api/

# COPY /code/go.mod /code/go.sum ./

# RUN go mod vendor

EXPOSE 80